### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by jacksonpradolima** [markuswagnergithub/SBSEcourse#1]
First of all, Great repository! 

So, some links for the external resources are broken, for instance, the SBSE introduction.

Can you take a look?

Thanks in advance

**Comment by markuswagnergithub** [comment]
Hi Jackson! Thanks a lot for your interest -- and for spotting the broken links. I'll check with Justyna if I can upload her slides to here. Give me a few days...

**Comment by markuswagnergithub** [comment]
Hi Jackson, Justyna kindly allowed me to upload the slides to the course. You can now find them in the respective folder. I have also taken the opportunity to update a few bits and pieces to the 2021 edition (to the extent possible) by adding 'recommended reading' and some comments to the Readme. Hope this helps! Thanks again for flagging the broken links.

**Comment by jacksonpradolima** [comment]
Hi @markuswagnergithub 
I'll take a look, thanks a lot!
